// One-shot setup: create .env.local (if missing), then migrate the DB, create
// the admin login, and seed example accounts + categories. Safe to re-run — it
// never overwrites an existing .env.local and seeding is idempotent.
//
//   npm install && npm run setup && npm run dev
//
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';

const ENV = '.env.local';
let createdEnv = false;
let username = 'admin';
let password = '';

function gen(n) {
  // URL/shell-safe token (no quoting headaches in .env)
  return randomBytes(n).toString('base64url').slice(0, n);
}

if (!fs.existsSync(ENV)) {
  password = gen(16);
  const secret = randomBytes(32).toString('hex');
  fs.writeFileSync(
    ENV,
    `# Generated by \`npm run setup\` on ${new Date().toISOString()}
# Web UI login — change APP_PASSWORD any time (or in the app under More).
APP_USERNAME=${username}
APP_PASSWORD=${password}
# Signs the session cookie. Keep secret; rotating it logs everyone out.
APP_SESSION_SECRET=${secret}
# Bearer token for /api/* (external clients like a Telegram bot). Optional.
MONEY_TRACKER_API_TOKEN=${gen(24)}
# Initial base currency (changeable in the UI). Any ISO code: USD, EUR, MYR, …
NEXT_PUBLIC_BASE_CURRENCY=USD
`,
    { mode: 0o600 },
  );
  createdEnv = true;
  console.log(`✓ wrote ${ENV} (login: ${username} / ${password})`);
} else {
  console.log(`• ${ENV} already exists — leaving it untouched`);
}

function run(label, args) {
  console.log(`\n▶ ${label}`);
  execFileSync('npx', args, { stdio: 'inherit' });
}

run('Creating database schema', ['tsx', 'scripts/migrate.ts']);
run('Creating admin login', ['tsx', 'scripts/seed-admin.ts']);
run('Seeding example accounts + categories', ['tsx', 'scripts/seed.ts']);

console.log('\n──────────────────────────────────────────────');
console.log('✓ Setup complete. Start the app with:  npm run dev');
console.log('  then open http://localhost:3000');
if (createdEnv) {
  console.log(`\n  Login:  ${username} / ${password}`);
  console.log('  (change it in the app under More → Change password)');
} else {
  console.log('\n  Log in with the APP_USERNAME / APP_PASSWORD in your .env.local');
}
console.log('\n  Optional: `npm run db:seed-demo` adds sample transactions to explore.');
console.log('──────────────────────────────────────────────');
